AS
BEGIN
SET NOCOUNT ON;
/*
MODIFIE DANS SYNC_SMS_GESTION_PRESTATION
DEFINI OPTI_REJECTED = SI U.ID EST NULL METS 1 SINON NULL
	OPTI_REJECTED_REASON = SI U.IS EST NULL METS 'USER NOT FOUND' SINON NULL
DANS SYNC_SMS_GESTION_PRESTATION as R
JOINTURE GAUCHE USERS_CONTACTS U ON U.XNUMDOSSIERADH = 8 CARACTERES A PARTIR DE LA DROITE ET ETAT = 'Adhérent' ET TEMPLATE is null
SI 2 CARACTERE DE GAUCHE DE NUM_ADHÉRENT = '01' ET LE NOMBRE DE CARACTERE = 10
*/
UPDATE SYNC_SMS_GESTION_PRESTATION
	SET OPTI_REJECTED = CASE WHEN U.ID IS NULL THEN 1 ELSE NULL END,
	    OPTI_REJECTED_REASON = CASE WHEN U.ID IS NULL THEN 'USER NOT FOUND' ELSE NULL END
FROM SYNC_SMS_GESTION_PRESTATION R
LEFT OUTER JOIN USERS_CONTACTS U ON U.XNUMDOSSIERADH = RIGHT(R.NUM_ADHÉRENT, 8) and ETAT = 'Adhérent' AND TEMPLATE is null
WHERE LEFT(R.NUM_ADHÉRENT, 2)  = '01' AND LEN(R.NUM_ADHÉRENT) = 10;

/*
MODIFIE DANS SYNC_SMS_GESTION_PRESTATION
DEFINI OPTI_REJECTED = SI U.ID EST NULL METS 1 SINON NULL
	OPTI_REJECTED_REASON = SI U.IS EST NULL METS 'USER NOT FOUND' SINON NULL
DANS SYNC_SMS_GESTION_PRESTATION as R
JOINTURE GAUCHE USERS_CONTACTS U ON U.XNUMDOSSIERADH = R.NUM_ADHÉRENT ET ETAT = 'Adhérent' ET TEMPLATE is null
SI LE NOMBRE DE CARACTERE DE R.NUM_ADHÉRENT INF A 8
*/
UPDATE SYNC_SMS_GESTION_PRESTATION
	SET OPTI_REJECTED = CASE WHEN U.ID IS NULL THEN 1 ELSE NULL END,
	    OPTI_REJECTED_REASON = CASE WHEN U.ID IS NULL THEN 'USER NOT FOUND' ELSE NULL END
FROM SYNC_SMS_GESTION_PRESTATION R
LEFT OUTER JOIN USERS_CONTACTS U ON U.XNUMDOSSIERADH = R.NUM_ADHÉRENT and ETAT = 'Adhérent'  AND TEMPLATE is null
WHERE LEN(R.NUM_ADHÉRENT) < 8;

/*
MODIFIE DANS SYNC_SMS_GESTION_PRESTATION
DEFINI OPTI_REJECTED = 2
	OPTI_REJECTED_REASON = SI xgsm EST NULL METS 'GSM NON RENSEIGNE GRA' SINON 'GSM GRA DIFFERENT DU FICHIER'
DANS SYNC_SMS_GESTION_PRESTATION as R
JOINTURE USERS_CONTACTS U ON U.XNUMDOSSIERADH = 8 CARACTERES A PARTIR DE LA DROITE ET ETAT = 'Adhérent' ET TEMPLATE is null
SI OPTI_REJECTED EST NULL ET 2 CARACTERE DE GAUCHE DE NUM_ADHÉRENT = '01' ET LE NOMBRE DE CARACTERE = 10 ET xgsm EST NULL DIFFERENT DE PORTABLE
*/
UPDATE SYNC_SMS_GESTION_PRESTATION
	SET OPTI_REJECTED = 2,
	    OPTI_REJECTED_REASON = CASE WHEN xgsm is NULL THEN 'GSM NON RENSEIGNE GRA' ELSE 'GSM GRA DIFFERENT DU FICHIER' END
FROM SYNC_SMS_GESTION_PRESTATION R
INNER JOIN USERS_CONTACTS U ON U.XNUMDOSSIERADH = RIGHT(R.NUM_ADHÉRENT, 8) and ETAT = 'Adhérent' AND TEMPLATE is null 
WHERE OPTI_REJECTED is null AND LEFT(R.NUM_ADHÉRENT, 2)  = '01' AND LEN(R.NUM_ADHÉRENT) = 10 and ISNULL(xgsm, '') <> PORTABLE;

/*
MODIFIE DANS SYNC_SMS_GESTION_PRESTATION
DEFINI OPTI_REJECTED = 2
	OPTI_REJECTED_REASON = SI xgsm EST NULL METS 'GSM NON RENSEIGNE GRA' SINON 'GSM GRA DIFFERENT DU FICHIER'
DANS SYNC_SMS_GESTION_PRESTATION as R
JOINTURE USERS_CONTACTS U ON U.XNUMDOSSIERADH = R.NUM_ADHÉRENT ET ETAT = 'Adhérent' ET TEMPLATE is null
SI OPTI_REJECTED EST NULL ET LE NOMBRE DE CARACTERE EST INFERIEUR A 8 ET NULL 
*/
UPDATE SYNC_SMS_GESTION_PRESTATION
	SET OPTI_REJECTED = 2,
	    OPTI_REJECTED_REASON = CASE WHEN xgsm is NULL THEN 'GSM NON RENSEIGNE GRA' ELSE 'GSM GRA DIFFERENT DU FICHIER' END
FROM SYNC_SMS_GESTION_PRESTATION R
INNER JOIN USERS_CONTACTS U ON U.XNUMDOSSIERADH = R.NUM_ADHÉRENT and ETAT = 'Adhérent' AND TEMPLATE is null 
WHERE OPTI_REJECTED is null AND LEN(R.NUM_ADHÉRENT) < 8 and ISNULL(xgsm, '') <> REPLACE(PORTABLE, ' ', '');

INSERT INTO SYNC_SMS_GESTION_PRESTATION_BACKUP
(CREATED_DT, NUM_ADHERENT, NUM_IDENTIFIANT, NOM, PRENOM, PORTABLE, ORG_NO, EXTRANET, OPTI_REJECTED, OPTI_REJECTED_REASON)
SELECT GETDATE(), NUM_ADHÉRENT, NUM_IDENTIFIANT, NOM, PRÉNOM, PORTABLE, ORG_NO, EXTRANET, OPTI_REJECTED, OPTI_REJECTED_REASON
FROM SYNC_SMS_GESTION_PRESTATION


SELECT   COUNT(*), NUM_ADHÉRENT, NUM_IDENTIFIANT, NOM, PRÉNOM, PORTABLE
FROM     SYNC_SMS_GESTION_PRESTATION
GROUP BY NUM_ADHÉRENT, NUM_IDENTIFIANT, NOM, PRÉNOM, PORTABLE
HAVING   COUNT(*) > 1

SELECT DISTINCT NUM_ADHÉRENT, NUM_IDENTIFIANT, NOM, PRÉNOM, PORTABLE
FROM SYNC_SMS_GESTION_PRESTATION
ORDER BY NUM_ADHÉRENT, NUM_IDENTIFIANT, NOM, PRÉNOM, PORTABLE

/*test*/
SELECT COUNT(DISTINCT PORTABLE)
FROM SYNC_SMS_GESTION_PRESTATION
WHERE OPTI_REJECTED is null OR OPTI_REJECTED in (0, 2)

INSERT INTO ACTION_SMS_GESTION_PRESTATION
( CREATED_DT, LISTID, ACTIONCODE, NUM_ADHERENT, NUM_IDENTIFIANT, NOM, PRENOM, PORTABLE, ORG_NO, EXTRANET)
SELECT DISTINCT GETDATE(), 4, 'A_TRAITER', NUM_ADHÉRENT, NUM_IDENTIFIANT, NOM, PRÉNOM, PORTABLE, ORG_NO, EXTRANET
FROM SYNC_SMS_GESTION_PRESTATION
WHERE OPTI_REJECTED is null OR OPTI_REJECTED in (0, 2)

UPDATE ACTION_SMS_GESTION_PRESTATION
	SET USERID = us.ID,
	    ACTIONCODE = CASE WHEN ISNULL(XGESTION_SMS, 0) = 1 THEN 'STOP_SMS' ELSE ACTIONCODE END,
	    GSM_INTERNATIONAL = '33' + RIGHT(REPLACE(PORTABLE, ' ', ''), 9)
FROM ACTION_SMS_GESTION_PRESTATION
LEFT OUTER JOIN USERS_CONTACTS us ON XNUMDOSSIERADH = RIGHT(NUM_ADHERENT, 8) and us.ETAT = 'Adhérent' AND TEMPLATE is null
WHERE ACTIONCODE = 'A_TRAITER' AND EXEC_DT is null AND LEFT(NUM_ADHERENT, 2)  = '01' AND LEN(NUM_ADHERENT) = 10;

UPDATE ACTION_SMS_GESTION_PRESTATION
	SET USERID = us.ID,
	    ACTIONCODE = CASE WHEN ISNULL(XGESTION_SMS, 0) = 1 THEN 'STOP_SMS' ELSE ACTIONCODE END,
	    GSM_INTERNATIONAL = '33' + Substring(REPLACE(PORTABLE, ' ', ''), 2, 9)
FROM ACTION_SMS_GESTION_PRESTATION
LEFT OUTER JOIN USERS_CONTACTS us ON XNUMDOSSIERADH = NUM_ADHERENT and us.ETAT = 'Adhérent' AND TEMPLATE is null
WHERE ACTIONCODE = 'A_TRAITER' AND EXEC_DT is null AND LEN(NUM_ADHERENT) < 8;


UPDATE ACTION_SMS_GESTION_PRESTATION
	SET USERID = us.ID,
	    ACTIONCODE = CASE WHEN XGESTION_SMS = 1 THEN 'STOP_SMS' ELSE ACTIONCODE END,
	    GSM_INTERNATIONAL = '33' + Substring(REPLACE(PORTABLE, ' ', ''), 2, 9)
FROM ACTION_SMS_GESTION_PRESTATION
LEFT OUTER JOIN USERS_CONTACTS us ON US.NOM = 'SALARIE'
WHERE ACTIONCODE = 'A_TRAITER' AND EXEC_DT is null AND LEFT(NUM_ADHERENT, 2)  = '09' AND LEN(NUM_ADHERENT) = 10;

END
